catalog/urls.py
from django.conf.urls import url

from .views import *

urlpatterns = [
    url(r'libro/(?P<id>[0-9]+)', book, name='book_detail'),
    url(r'libro/registrar', register_book, name='book_registration'),
    url(r'autores$', author_index, name='home'),
    url(r'autor/(?P<id>[0-9]+)', author_detail, name='author_detail'),
    url(r'pais/(?P<id>[0-9]+)$', country_detail, name='country_detail'),
    url(r'^$', catalog_index, name='catalog_index')
]

librolibre/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.views.generic import TemplateView


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^catalog/', include('catalog.urls', namespace='catalog'))
]

catalog/models.py
from django.db import models

# Create your models here.

class Book(models.Model):
    title = models.CharField(max_length=140)
    description = models.CharField(max_length=500, blank=True, null=True)
    pages = models.PositiveIntegerField(default=0)
    author = models.ForeignKey(
        'Author',
        on_delete=models.PROTECT,
        related_name='books'
    )

    def __str__(self):
        return "Título: %s, p. %s" % (self.title, self.pages)


class Author(models.Model):
    name = models.CharField(max_length=140)
    biography = models.CharField(max_length=1000)
    country = models.ForeignKey(
        'Country',
        on_delete=models.PROTECT,
        related_name='authors',
        null=True,
        blank=True
        )

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

catalog/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseNotFound

from .models import Book, Author, Country
# Create your views here.

# daniel nos va explicar que tiene Request
def catalog_index(request):
    """
    Vista basada en función
    """
    books = Book.objects.all()

    return render(
        request,
        'catalog/index.html',
        context={"books": books}
    )


def book(request, id):
    book = get_object_or_404(Book, pk=id)

    context = {
        "book": book
    }
    return render(
        request,
        'catalog/book.html',
        context=context)


def author_index(request):
    authors = Author.objects.all()
    context = {
        "authors": authors
    }
    return render(
        request,
        'catalog/authors.html',
        context=context
    )

def author_detail(request, id):
    # author = Author.objects.get(pk=id)
    author = get_object_or_404(Author, pk=id)
    context = {
        "author": author
    }
    return render(
        request,
        'catalog/author_detail.html',
        context=context
    )

def country_detail(request, id):
    country = get_object_or_404(Country, pk=id)
    context = {
        "country": country
    }

    return render(
        request,
        'catalog/country_detail.html',
        context=context
    )


def register_book(request):

    if request.method == 'POST':
        # Get information
        title = request.POST.get('title')
        description = request.POST.get('description')
        author = request.POST.get('author')

        # stored_author = Author.objects.get(pk=author)

        # Creating Object
        book = Book.objects.create(
            title=title,
            description=description,
            author_id=author
        )

        # Return Response
        context = {
            "book": book
        }
        return render(
            request,
            'catalog/book.html',
            context=context
        )

    else:
        return render(
            request, 
            'catalog/book_registration.html')

catalog/templates/catalog/author.html
{% extends 'base.html' %}

{% block content %}
    <h2>Autores</h2>
    <p> Tenemos libros de los siguientes autores</p>
    <ul>
        {% for author in authors %}
            <li>{{ author.name }}</li>
        {% endfor %}
    </ul>

{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ author.name }}</h2>
<p> {{ author.biography }}</p>

<h4>País</h4>
<a href="{% url 'catalog:country_detail' author.country.id %}">{{ author.country.name }}</a>

<h3> Libros </h3>


<ul>
{% for book in author.books.all %}
    <li>{{ book.title }}</li>
{% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/authors.html
{% extends 'base.html' %}

{% block content %}
    <h2>Autores</h2>
    <p> Tenemos libros de los siguientes autores</p>
    <ul>
        {% for author in authors %}
            <li><a href="{% url 'author_detail' author.id %}">{{ author.name }}</li>
        {% endfor %}
    </ul>

{% endblock %}

catalog/templates/catalog/book.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ book.title }}</h2>
<p> {{ book.description }}</p>

<h3>Autor</h3>

    {{ book.author.name }}
    <br>
    {{ book.author.country.name }}

{% endblock %}

catalog/templates/catalog/book_registration.html
{% extends 'base.html' %}

{% block content %}

<h2>Registra tu libro</h2>

<form method='POST'>
    {% csrf_token %}
    <div>
        <label for="title"> Título del libro</label>
        <input type="text" name="title" placeholder="El Principito">
    </div>
    <div>
        <label for="description"> Descripción</label>
        <textarea name="description" placeholder="El Principito..."> </textarea>
    </div>
    <dir>
        <label for="author"> Autor </label>
        <select name="author">
            <option value=""> Selecciona un autor </option>
            <option value="1"> Antoine Saint Exupery </option>
        </select>
    </dir>
    <input type="submit" value="Registrar">
</form>

{% endblock %}

catalog/templates/catalog/country_detail.html
{% extends 'base.html' %}

{% block content %}

<h2>{{ country.name }}</h2>

<h4>Autores</h4>
<ul>
{% for author in country.authors.all %}
    <li><a href="{% url 'catalog:author_detail' author.id %}">{{ author.name }} </a></li>
{% endfor %}
</ul>
{% endblock %}

catalog/templates/catalog/index.html
{% extends 'base.html' %}

{% block content %}
<h2> Bienvenido a Libro Libre</h2>
<p>Estos son los libros disponibles</p>

<ul>
    {% for book in books %}
        <li><a href="{% url 'catalog:book_detail' book.id %}">{{ book.title }}</a> - 
            <a href="{% url 'catalog:author_detail' book.author.id %}">{{ book.author.name }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

librolibre/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Libro Libre</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css'%}">
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col">
                <img src="{% static 'librolibre.png' %}" class='app_logo' alt="App logo">
                <h1><a href="{% url 'home' %}"> Libro Libre </a></h1>
            </div>
        </div>

        <div class="row">
            <div class="col">
                {% block content %} Aquí va el contenido {% endblock %}
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js"></script>
</body>
</html>

librolibre/templates/home.html
{% extends 'base.html' %}

{% block content %}

¡Bienvenido a LIBRO LIBRE!

{% endblock content %}